// This file is automatically generated. Do not edit it directly.
// Regenerated 2026-06-14 after the artifacts migration.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      applications: {
        Row: {
          applied_at: string
          id: string
          job_id: string
          notes: string | null
          status: string
          user_id: string
        }
        Insert: {
          applied_at?: string
          id?: string
          job_id: string
          notes?: string | null
          status?: string
          user_id: string
        }
        Update: {
          applied_at?: string
          id?: string
          job_id?: string
          notes?: string | null
          status?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "applications_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      artifacts: {
        Row: {
          content: Json
          created_at: string
          id: string
          job_id: string | null
          kind: string
          model: string | null
          public_slug: string | null
          updated_at: string
          user_id: string
          visibility: string
        }
        Insert: {
          content?: Json
          created_at?: string
          id?: string
          job_id?: string | null
          kind: string
          model?: string | null
          public_slug?: string | null
          updated_at?: string
          user_id: string
          visibility?: string
        }
        Update: {
          content?: Json
          created_at?: string
          id?: string
          job_id?: string | null
          kind?: string
          model?: string | null
          public_slug?: string | null
          updated_at?: string
          user_id?: string
          visibility?: string
        }
        Relationships: [
          {
            foreignKeyName: "artifacts_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      audits: {
        Row: {
          accent_color: string | null
          audit_data: Json
          audit_label: string | null
          company_name: string
          created_at: string
          duration_seconds: number | null
          id: string
          is_published: boolean
          job_link: string | null
          pdf_path: string | null
          role_name: string | null
          slug: string | null
          user_id: string
        }
        Insert: {
          accent_color?: string | null
          audit_data: Json
          audit_label?: string | null
          company_name: string
          created_at?: string
          duration_seconds?: number | null
          id?: string
          is_published?: boolean
          job_link?: string | null
          pdf_path?: string | null
          role_name?: string | null
          slug?: string | null
          user_id: string
        }
        Update: {
          accent_color?: string | null
          audit_data?: Json
          audit_label?: string | null
          company_name?: string
          created_at?: string
          duration_seconds?: number | null
          id?: string
          is_published?: boolean
          job_link?: string | null
          pdf_path?: string | null
          role_name?: string | null
          slug?: string | null
          user_id?: string
        }
        Relationships: []
      }
      company_requests: {
        Row: {
          careers_url: string | null
          company_name: string
          created_at: string
          id: string
          note: string | null
          status: string
          user_id: string
        }
        Insert: {
          careers_url?: string | null
          company_name: string
          created_at?: string
          id?: string
          note?: string | null
          status?: string
          user_id: string
        }
        Update: {
          careers_url?: string | null
          company_name?: string
          created_at?: string
          id?: string
          note?: string | null
          status?: string
          user_id?: string
        }
        Relationships: []
      }
      device_fingerprints: {
        Row: {
          audit_id: string
          created_at: string
          fingerprint_id: string
          id: string
          user_id: string
        }
        Insert: {
          audit_id: string
          created_at?: string
          fingerprint_id: string
          id?: string
          user_id: string
        }
        Update: {
          audit_id?: string
          created_at?: string
          fingerprint_id?: string
          id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "device_fingerprints_audit_id_fkey"
            columns: ["audit_id"]
            isOneToOne: false
            referencedRelation: "audits"
            referencedColumns: ["id"]
          },
        ]
      }
      feedback: {
        Row: {
          created_at: string
          id: string
          message: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          message: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          message?: string
          user_id?: string
        }
        Relationships: []
      }
      companies: {
        Row: {
          careers_url: string | null
          coord_precision: string
          headcount_bucket: string | null
          hq_city: string | null
          hq_country: string | null
          lat: number | null
          linkedin_url: string | null
          lng: number | null
          logo_domain: string | null
          name: string
          open_roles_count: number | null
          sector: string | null
          slug: string
          source: string | null
          stage: string | null
          uk_sponsor_status: string | null
          updated_at: string
          website: string | null
        }
        Insert: {
          careers_url?: string | null
          coord_precision?: string
          headcount_bucket?: string | null
          hq_city?: string | null
          hq_country?: string | null
          lat?: number | null
          linkedin_url?: string | null
          lng?: number | null
          logo_domain?: string | null
          name: string
          open_roles_count?: number | null
          sector?: string | null
          slug: string
          source?: string | null
          stage?: string | null
          uk_sponsor_status?: string | null
          updated_at?: string
          website?: string | null
        }
        Update: {
          careers_url?: string | null
          coord_precision?: string
          headcount_bucket?: string | null
          hq_city?: string | null
          hq_country?: string | null
          lat?: number | null
          linkedin_url?: string | null
          lng?: number | null
          logo_domain?: string | null
          name?: string
          open_roles_count?: number | null
          sector?: string | null
          slug?: string
          source?: string | null
          stage?: string | null
          uk_sponsor_status?: string | null
          updated_at?: string
          website?: string | null
        }
        Relationships: []
      }
      jobs: {
        Row: {
          city: string | null
          company: string
          company_id: string | null
          created_at: string
          first_seen_at: string
          id: string
          is_live: boolean
          jd_text: string | null
          location: string | null
          posted_at: string | null
          remote: boolean
          seniority: string | null
          source: string | null
          title: string
          url: string
        }
        Insert: {
          city?: string | null
          company: string
          company_id?: string | null
          created_at?: string
          first_seen_at?: string
          id?: string
          is_live?: boolean
          jd_text?: string | null
          location?: string | null
          posted_at?: string | null
          remote?: boolean
          seniority?: string | null
          source?: string | null
          title: string
          url: string
        }
        Update: {
          city?: string | null
          company?: string
          company_id?: string | null
          created_at?: string
          first_seen_at?: string
          id?: string
          is_live?: boolean
          jd_text?: string | null
          location?: string | null
          posted_at?: string | null
          remote?: boolean
          seniority?: string | null
          source?: string | null
          title?: string
          url?: string
        }
        Relationships: [
          {
            foreignKeyName: "jobs_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["slug"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          citizenship: string | null
          created_at: string
          cv_text: string | null
          display_name: string | null
          email: string | null
          eu_work_authorized: boolean | null
          id: string
          languages: string[] | null
          onboarded_at: string | null
          open_to_remote: boolean | null
          target_cities: string[] | null
          target_seniority: string | null
          updated_at: string
          username: string | null
        }
        Insert: {
          avatar_url?: string | null
          citizenship?: string | null
          created_at?: string
          cv_text?: string | null
          display_name?: string | null
          email?: string | null
          eu_work_authorized?: boolean | null
          id: string
          languages?: string[] | null
          onboarded_at?: string | null
          open_to_remote?: boolean | null
          target_cities?: string[] | null
          target_seniority?: string | null
          updated_at?: string
          username?: string | null
        }
        Update: {
          avatar_url?: string | null
          citizenship?: string | null
          created_at?: string
          cv_text?: string | null
          display_name?: string | null
          email?: string | null
          eu_work_authorized?: boolean | null
          id?: string
          languages?: string[] | null
          onboarded_at?: string | null
          open_to_remote?: boolean | null
          target_cities?: string[] | null
          target_seniority?: string | null
          updated_at?: string
          username?: string | null
        }
        Relationships: []
      }
      purchases: {
        Row: {
          created_at: string
          credits: number
          id: string
          product_id: string
          stripe_session_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          credits: number
          id?: string
          product_id: string
          stripe_session_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          credits?: number
          id?: string
          product_id?: string
          stripe_session_id?: string
          user_id?: string
        }
        Relationships: []
      }
      scores: {
        Row: {
          id: string
          job_id: string
          rubric_version: string
          score: number | null
          scored_at: string
          signals: Json | null
          user_id: string
        }
        Insert: {
          id?: string
          job_id: string
          rubric_version?: string
          score?: number | null
          scored_at?: string
          signals?: Json | null
          user_id: string
        }
        Update: {
          id?: string
          job_id?: string
          rubric_version?: string
          score?: number | null
          scored_at?: string
          signals?: Json | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "scores_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      usage_events: {
        Row: {
          cost_usd: number | null
          created_at: string
          id: string
          input_tokens: number | null
          kind: string
          model: string | null
          output_tokens: number | null
          user_id: string
        }
        Insert: {
          cost_usd?: number | null
          created_at?: string
          id?: string
          input_tokens?: number | null
          kind: string
          model?: string | null
          output_tokens?: number | null
          user_id: string
        }
        Update: {
          cost_usd?: number | null
          created_at?: string
          id?: string
          input_tokens?: number | null
          kind?: string
          model?: string | null
          output_tokens?: number | null
          user_id?: string
        }
        Relationships: []
      }
      whitelisted_emails: {
        Row: {
          created_at: string
          email: string
          id: string
        }
        Insert: {
          created_at?: string
          email: string
          id?: string
        }
        Update: {
          created_at?: string
          email?: string
          id?: string
        }
        Relationships: []
      }
    }
    Views: {
      public_profiles: {
        Row: {
          avatar_url: string | null
          display_name: string | null
          id: string | null
          username: string | null
        }
        Insert: {
          avatar_url?: string | null
          display_name?: string | null
          id?: string | null
          username?: string | null
        }
        Update: {
          avatar_url?: string | null
          display_name?: string | null
          id?: string | null
          username?: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      count_audits_by_fingerprint: {
        Args: { p_fingerprint: string }
        Returns: number
      }
      generate_audit_slug: {
        Args: { p_company: string; p_user_id: string }
        Returns: string
      }
      get_global_avg_duration: { Args: never; Returns: number }
      link_jobs_to_companies: { Args: never; Returns: number }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
